name: Playwright API Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      EXPIRED_AUTH_TOKEN: ${{ secrets.EXPIRED_AUTH_TOKEN }}
      MALFORMED_TOKEN: ${{ secrets.MALFORMED_TOKEN}}
      PERSONALID: ${{ secrets.PERSONALID}}
      MOBILENUMBERTEST1: ${{ secrets.MOBILENUMBERTEST1}}
      MOBILENUMBERTEST2: ${{ secrets.MOBILENUMBERTEST2}}
      EMAILTEST1: ${{ secrets.EMAILTEST1}}
      EMAILTEST2: ${{ secrets.EMAILTEST2}}
      TRIAGEINTERVIEWID: ${{ secrets.TRIAGEINTERVIEWID }}
      PERSONEXTERNALID: ${{ secrets.PERSONEXTERNALID}}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Run Playwright API tests
        run: npx playwright test --project=API

      - name: Upload Playwright report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report
